server:
    port: 8080

spring:
  datasource:
    druid:
      masterDB:
        driverClassName: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.3.175:1521/orcl
        username: znwlxg
        password: znwlxg
        initialSize: 2
        minIdle: 2
        maxActive: 5
        validationQuery: SELECT 1 from dual
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        maxWait: 6000
        filters: wall,stat,slf4j
      slaveDB:
        driverClassName: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.88.101:1521/orcl
        username: ZNWLXG
        password: znwlxg
        initialSize: 2
        minIdle: 2
        maxActive: 5
        validationQuery: SELECT 1 from dual
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        maxWait: 6000

mybatis:
    mapperLocations: classpath*:com/qdtz/SpringWebService/mapper/Impl/*.xml

logging:
    level:
        com.qdtz.SpringWebService.mapper: TRACE
        


  